[[language]]
name = "c"
auto-format = false
language-id = "c"
language-servers = ["clangd"]


[[language]]
name = "python"
auto-format = false
language-id = "python"
language-servers = ["ruff-lsp", "pyright"]

# TypeScript
[[language]]
name = "typescript"
file-types = ["ts"]
roots = ["package.json", "tsconfig.json", "jsconfig.json"]
language-servers = ["ts_ls"]

# TypeScript React
[[language]]
name = "tsx"
file-types = ["tsx"]
roots = ["package.json", "tsconfig.json", "jsconfig.json"]
language-servers = ["ts_ls", "emmet_ls"]

# JavaScript
[[language]]
name = "javascript"
file-types = ["js"]
roots = ["package.json", "tsconfig.json", "jsconfig.json"]
language-servers = ["ts_ls"]

# JavaScript React
[[language]]
name = "jsx"
file-types = ["jsx"]
roots = ["package.json", "tsconfig.json", "jsconfig.json"]
language-servers = ["ts_ls", "emmet_ls"]

# Emmet LSP
[language-server.emmet_ls]
command = "emmet-language-server"
args = ["--stdio"]

# TypeScript LSP
[language-server.ts_ls]
command = "typescript-language-server"
args = ["--stdio"]


[language-server.ruff-lsp]
command = "ruff-lsp"
args = ["server"]
